### ISSUE TITLE
Causes crash on linux (probably also MacOS)

### ISSUE THREAD

**Issue by Jemsterr** [PsychoDad9999/ONI-Mods#1]
Whenever I finish a cleaning cycle on the Ore Scrubber, the game silently crashes to desktop.  The player.log wasn't much help tracking it down, but finally I saw it happen, and it is 100% reproducible.

This is the log:
Caught fatal signal - signo:11 code:128 errno:0 addr:(nil)
Obtained 3 stack frames.
#0  0x007f1e1cba4980 in funlockfile
#1  0x000000415a6ce0 in (Unknown)
#2  0x000000420d5c28 in StateMachineUpdater/BucketGroup:AdvanceOneSubTick (single)

**Comment by PsychoDad9999** [comment]
Sorry for the late response. I've never seen a crash on windows, maybe it's related only to the linux version of the game. 

Please provide more information (like Game Version and Mod Version)

Do you have other mods enabled? Can you reproduce the crash if you disable all mods except the Ore Scrubber mod?

**Comment by PsychoDad9999** [comment]
I was able to reproduce the issue on a Linux VM.

**Comment by PsychoDad9999** [comment]
Fixed in version 1.4

**Comment by Jemsterr** [comment]
Confirmed fixed.  Thanks. Sorry I didn't get around to answering your questions.
